from __future__ import annotations
import html
from pathlib import Path
from typing import Any

def esc(v): return html.escape(str(v if v is not None else ''))
def badge(label,value,status='neutral'):
    return f'<div class="metric {status}"><span>{esc(label)}</span><strong>{esc(value)}</strong></div>'
def status_class(value):
    s=str(value).upper(); return 'pass' if s in {'PASS','DONE','COMPLETE','AVAILABLE'} else ('fail' if s in {'FAIL','GAPS_OPEN','UNAVAILABLE'} else 'warn')
def rows(items,cols,empty='Nessun dato'):
    if not items: return f'<tr><td colspan="{len(cols)}" class="muted">{esc(empty)}</td></tr>'
    out=[]
    for item in items:
        out.append('<tr>'+''.join(f'<td>{esc(item.get(k,""))}</td>' for k in cols)+'</tr>')
    return ''.join(out)
def render_session_dashboard(state:dict[str,Any],output:str|Path)->Path:
    req=state.get('request',{}); metrics=state.get('metrics',{}); setup=state.get('setup',{}); mining=state.get('mining',{}); style=state.get('style_profile',{}); quality=state.get('quality',{}); claims=state.get('claim_ledger',[]); sources=state.get('sources',[]); evidence=state.get('artifact_evidence',[]); dod=state.get('dod',[]); bench=state.get('benchmark',{}); completion=state.get('completion',{}); contradictions=state.get('contradictions',[]); limits=state.get('limits',[]); artifacts=state.get('artifacts',[]); runtime=state.get('runtime',{}); source_intel=state.get('source_intelligence',{})
    done=sum(1 for d in dod if d.get('status')=='DONE'); material=sum(1 for c in claims if c.get('material',True)); supported=sum(1 for c in claims if c.get('status') in {'SUPPORTED','VERIFIED'}); inferred=sum(1 for c in claims if c.get('claim_type')=='strong_inference'); qstatus=quality.get('status','NOT_RUN'); bscore=(bench.get('score') or {}).get('heading_recall_soft','n/a')
    checks=(quality.get('style') or {}).get('checks',[])
    page=f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Juriscribe | verbale scientifico di sessione</title><style>
:root{{--ink:#20211f;--paper:#f5f1e8;--line:#cfc7b8;--green:#2e6844;--amber:#966b16;--red:#8c3030;--muted:#6d6a63}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font-family:Georgia,'Times New Roman',serif;line-height:1.48}}main{{max-width:1240px;margin:auto;padding:34px}}h1,h2,h3,th,.eyebrow,.metric span{{font-family:Arial,sans-serif}}header{{border-bottom:4px solid var(--ink);padding-bottom:18px;margin-bottom:20px}}.eyebrow{{font-weight:700;font-size:12px;letter-spacing:.14em;text-transform:uppercase}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}}.metric{{background:#fff;border-left:5px solid var(--ink);padding:12px}}.metric.pass{{border-left-color:var(--green)}}.metric.warn{{border-left-color:var(--amber)}}.metric.fail{{border-left-color:var(--red)}}.metric span{{display:block;font-size:11px;text-transform:uppercase;color:var(--muted)}}.metric strong{{font-size:20px}}section{{background:#fff;border:1px solid var(--line);padding:20px;margin:14px 0;border-radius:8px}}table{{width:100%;border-collapse:collapse;font-size:.94rem}}th,td{{border-bottom:1px solid #e6dfd3;padding:8px;vertical-align:top;text-align:left}}th{{font-size:.78rem;text-transform:uppercase;letter-spacing:.04em}}.muted{{color:var(--muted)}}.callout{{border-left:4px solid var(--amber);padding:10px 14px;background:#fbf7ef}}code{{background:#eee8dc;padding:2px 5px;border-radius:3px}}ul{{margin-top:.4rem}}
</style></head><body><main><header><div class="eyebrow">iSeneca · verbale giuridico-scientifico-editoriale</div><h1>{esc(req.get('summary') or 'Lavorazione corrente')}</h1><p>Sessione <code>{esc(state.get('session_id'))}</code>. La dashboard espone evidenze, stati e limiti auditabili; non espone chain-of-thought.</p></header>
<div class="grid">{badge('Fase',state.get('phase'),status_class(state.get('phase')))}{badge('DoD',f'{done}/{len(dod)}','pass' if dod and done==len(dod) else 'warn')}{badge('Quality gate',qstatus,status_class(qstatus))}{badge('Claim coverage',source_intel.get('coverage_status','NOT_STARTED'),status_class(source_intel.get('coverage_status')))}{badge('No novelty vs DoD',metrics.get('dod_no_novelty_streak',0),'pass' if metrics.get('dod_no_novelty_streak',0)>=10000 else 'warn')}{badge('Completion',completion.get('eligible',False),'pass' if completion.get('eligible') else 'warn')}</div>
<section><h2>1. Perimetro dell'incarico e autorità umana</h2><p>{esc(req.get('raw',''))}</p><h3>Setup accettato</h3><table><tbody>{''.join(f'<tr><th>{esc(k)}</th><td>{esc(v)}</td></tr>' for k,v in setup.get('accepted',{}).items()) or '<tr><td class="muted">Setup non ancora accettato</td></tr>'}</tbody></table><p class="callout"><strong>Regola:</strong> ogni parametro accettato deve essere rappresentato da un DoD bloccante. Le scelte interpretative umane restano distinguibili dalle inferenze iSeneca.</p></section>
<section><h2>2. Corpus effettivamente letto</h2><table><thead><tr><th>ID</th><th>Titolo/sommario</th><th>Tipo</th><th>Lettura diretta</th><th>Verifica</th></tr></thead><tbody>{rows(sources,['id','title','source_type','direct_read','verified_at'],'Nessuna fonte registrata')}</tbody></table></section>
<section><h2>3. Mining e continuità editoriale</h2><div class="grid">{badge('Mining',mining.get('mining_status','NOT_RUN'))}{badge('Parole corpus',mining.get('surface',{}).get('word_count',0))}{badge('Registro',style.get('register','n/a'))}{badge('Quality body words',quality.get('body_word_count','n/a'))}</div><h3>Style checks</h3><table><thead><tr><th>Check</th><th>Stato</th><th>Scostamento</th></tr></thead><tbody>{rows(checks,['id','status','value'],'Audit stile non eseguito')}</tbody></table><p><strong>Nota metodologica:</strong> l'apparato di fonti è escluso dal calcolo del ritmo stilistico; la segmentazione in sezioni è misurata separatamente per intercettare over-sectioning.</p></section>
<section><h2>4. Claim, fonti e tracciabilità nell'artefatto</h2><div class="grid">{badge('Claim materiali',material)}{badge('Supportati/verificati',supported)}{badge('Inferenze forti',inferred)}{badge('Evidence locator',len(evidence))}</div><table><thead><tr><th>Claim</th><th>Tipo</th><th>Stato</th><th>Fonti</th></tr></thead><tbody>{''.join(f'<tr><td>{esc(c.get("text") or c.get("id"))}</td><td>{esc(c.get("claim_type"))}</td><td>{esc(c.get("status"))}</td><td>{esc(c.get("support_source_ids",[]))}</td></tr>' for c in claims) or '<tr><td colspan="4" class="muted">Nessun claim materializzato</td></tr>'}</tbody></table><p><strong>Apparato visibile:</strong> {esc((quality.get('reference_apparatus') or {}).get('status','NOT_EVALUATED'))}; <strong>claim→fonte→pinpoint→artefatto:</strong> {esc((quality.get('claim_traceability') or {}).get('status','NOT_EVALUATED'))}.</p></section>
<section><h2>5. DoD, contraddizioni e prova di completamento</h2><table><thead><tr><th>DoD</th><th>Tipo</th><th>Atteso</th><th>Stato</th><th>Evidenza</th></tr></thead><tbody>{''.join(f'<tr><td>{esc(d.get("id"))}</td><td>{esc(d.get("kind"))}</td><td>{esc(d.get("expected",""))}</td><td>{esc(d.get("status"))}</td><td>{esc(d.get("evidence",[]))}</td></tr>' for d in dod) or '<tr><td colspan="5" class="muted">DoD non congelati</td></tr>'}</tbody></table><p><strong>Contraddizioni aperte:</strong> {esc(len([c for c in contradictions if c.get("status","OPEN")!='RESOLVED']))}. <strong>Completion gate:</strong> {esc(completion.get('reason','non valutato'))}.</p></section>
<section><h2>6. Benchmark monografico cieco</h2><p><strong>Monografia:</strong> {esc(bench.get('monograph','non eseguito'))}</p><p><strong>Integrità blind:</strong> {esc((bench.get('score') or {}).get('blind_integrity','n/a'))}; <strong>recall strutturale:</strong> {esc(bscore)}.</p><p class="muted">Il benchmark misura capacità di extrapolazione strutturale. Non prova verità giuridica; il runtime richiede un commitment esterno della reference nascosta per evitare benchmark hard-coded o leakage.</p></section>
<section><h2>7. Limiti reali e capacità host</h2><table><thead><tr><th>Limite</th><th>Impatto</th><th>Mitigazione</th></tr></thead><tbody>{rows(limits,['id','impact','mitigation'],'Nessun limite registrato')}</tbody></table><h3>Capability matrix</h3><table><tbody>{''.join(f'<tr><th>{esc(k)}</th><td>{esc(v)}</td></tr>' for k,v in runtime.get('capabilities',{}).items()) or '<tr><td class="muted">Non registrata</td></tr>'}</tbody></table></section>
<section><h2>8. Artefatti e readback</h2><table><thead><tr><th>ID</th><th>Sommario</th><th>Path</th><th>Readback</th></tr></thead><tbody>{rows(artifacts,['id','summary','path','readback'],'Nessun artefatto')}</tbody></table></section>
</main></body></html>'''
    out=Path(output); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(page,encoding='utf-8'); return out
