from __future__ import annotations
import html
from pathlib import Path
from typing import Any

HUMAN_KIND={"CLAIM":"tesi/affermazione","RULE":"regola","DEFINITION":"definizione","EXCEPTION":"eccezione","QUALIFICATION":"qualificazione","ARGUMENT":"argomento","COUNTERARGUMENT":"controargomento","CONCLUSION":"conclusione","OPEN_ISSUE":"questione aperta","QUESTION":"questione","INFERENCE":"inferenza","CONCEPT":"concetto"}
HUMAN_REL={"SUPPORTS":"sostiene","CONTRADICTS":"contraddice","QUALIFIES":"qualifica","DEPENDS_ON":"dipende da","DEFINES":"definisce","DISTINGUISHES":"distingue da","ANTICIPATES":"prepara","RECALLS":"richiama","DEVELOPS":"sviluppa","AVOIDS_DUPLICATION_OF":"non deve duplicare","INFERRED_FROM":"deriva da"}
def esc(v): return html.escape(str(v if v is not None else ''))
def sc(v):
    s=str(v).upper(); return 'ok' if s in {'PASS','DONE','COMPLETE','AVAILABLE','READY','ACCEPTED'} or v is True else ('bad' if s in {'FAIL','GAPS_OPEN','UNAVAILABLE','RETICULUM_INVALID'} else 'wait')
def pill(label,value): return f'<div class="pill {sc(value)}"><span>{esc(label)}</span><b>{esc(value)}</b></div>'
def table_rows(items,columns,empty='Nessun elemento registrato'):
    if not items:return f'<tr><td colspan="{len(columns)}" class="muted">{esc(empty)}</td></tr>'
    out=[]
    for item in items: out.append('<tr>'+''.join(f'<td>{esc(fn(item) if callable(fn) else item.get(fn,""))}</td>' for _,fn in columns)+'</tr>')
    return ''.join(out)
def head(columns): return ''.join(f'<th>{esc(label)}</th>' for label,_ in columns)
def blockers(state):
    reason=(state.get('completion') or {}).get('reason','')
    if not reason or reason=='PASS': return []
    return [x.strip() for x in reason.split(';') if x.strip()]

def render_session_dashboard(state:dict[str,Any],output:str|Path)->Path:
    req=state.get('request',{}); ret=state.get('reticulum',{}); units=state.get('epistemic_units',[]); rels=state.get('relations',[]); sources=state.get('sources',[]); setup=state.get('setup',{}); dod=state.get('dod',[]); claims=state.get('claim_ledger',[]); quality=state.get('quality',{}); metrics=state.get('metrics',{}); sim=state.get('simulations',{}); comp=state.get('compression',{}); completion=state.get('completion',{}); artifacts=state.get('artifacts',[]); evidence=state.get('artifact_evidence',[]); contradictions=state.get('contradictions',[]); gen=state.get('generation_contract',{}); admission=state.get('admission',{}); source_intel=state.get('source_intelligence',{}); bench=state.get('benchmark',{}); limits=state.get('limits',[])
    done=sum(1 for d in dod if d.get('status')=='DONE'); release='PRONTO PER CONSEGNA' if completion.get('eligible') else 'NON PRONTO'; block=blockers(state)
    by_id={u.get('id'):u for u in units}
    cross=[]
    for r in rels:
        a,b=by_id.get(r.get('source'),{}),by_id.get(r.get('target'),{})
        if a.get('chapter') and b.get('chapter') and a.get('chapter')!=b.get('chapter'): cross.append({"from":a.get('chapter'),"relation":HUMAN_REL.get(r.get('predicate'),r.get('predicate')),"to":b.get('chapter'),"subject":a.get('text'),"target":b.get('text')})
    inference=[c for c in claims if c.get('claim_type')=='strong_inference']
    source_claim_count={s.get('id'):sum(1 for c in claims if s.get('id') in c.get('support_source_ids',[])) for s in sources}
    unit_cols=[('ID','id'),('Funzione',lambda x:HUMAN_KIND.get(x.get('kind'),x.get('kind'))),('Proposizione','text'),('Capitolo','chapter'),('Passo sorgente','source_locator'),('Stato','status')]
    rel_cols=[('Da','source'),('Relazione',lambda x:HUMAN_REL.get(x.get('predicate'),x.get('predicate'))),('A','target'),('Ragione sintetica','rationale')]
    source_cols=[('Fonte','title'),('Tipo','source_type'),('Ruolo','role'),('Lettura diretta','direct_read'),('Verificata','verified_at'),('Claim',lambda x:source_claim_count.get(x.get('id'),0)),('Voce bibliografica','bibliography_entry')]
    dod_cols=[('DoD','id'),('Tipo','kind'),('Atteso','expected'),('Stato','status'),('Evidenza','evidence')]
    art_cols=[('Artefatto','summary'),('Percorso','path'),('Readback','readback')]
    page=f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Juriscribe — fascicolo di lavorazione</title><style>
:root{{--ink:#1b1f23;--paper:#f3f0e8;--card:#fffdfa;--line:#d4ccbd;--green:#235f43;--amber:#8a6416;--red:#8b2f2f;--blue:#345d7e;--muted:#6c6a66}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:16px/1.5 Georgia,'Times New Roman',serif}}main{{max-width:1320px;margin:auto;padding:28px}}h1,h2,h3,th,.kicker,.pill span,.decision{{font-family:Arial,sans-serif}}header{{background:var(--card);border-top:6px solid var(--ink);border-bottom:1px solid var(--line);padding:24px;margin-bottom:16px}}.kicker{{font-size:12px;font-weight:800;letter-spacing:.13em;text-transform:uppercase;color:var(--blue)}}.decision{{font-size:28px;font-weight:800;margin:.5rem 0}}.decision.ok{{color:var(--green)}}.decision.wait{{color:var(--amber)}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(195px,1fr));gap:10px}}.pill{{background:var(--card);padding:12px;border-left:5px solid var(--blue);border-radius:4px}}.pill.ok{{border-left-color:var(--green)}}.pill.wait{{border-left-color:var(--amber)}}.pill.bad{{border-left-color:var(--red)}}.pill span{{display:block;font-size:11px;text-transform:uppercase;color:var(--muted)}}.pill b{{font-size:18px}}section{{background:var(--card);border:1px solid var(--line);border-radius:7px;padding:20px;margin:14px 0}}.why{{background:#f8f4ea;border-left:4px solid var(--blue);padding:10px 13px}}.block{{background:#fff4f2;border-left:4px solid var(--red);padding:10px 14px}}.good{{background:#f2f8f3;border-left:4px solid var(--green);padding:10px 14px}}table{{width:100%;border-collapse:collapse;font-size:.91rem}}th,td{{border-bottom:1px solid #e6dfd4;padding:8px;text-align:left;vertical-align:top}}th{{font-size:.73rem;text-transform:uppercase;letter-spacing:.04em}}.muted{{color:var(--muted)}}code{{background:#eee8dc;padding:2px 5px;border-radius:3px}}details{{margin:.5rem 0}}ul{{margin:.4rem 0 0 1.2rem}}@media(max-width:700px){{main{{padding:10px}}table{{display:block;overflow:auto}}}}
</style></head><body><main>
<header><div class="kicker">Juriscribe · fascicolo giuridico-scientifico-editoriale</div><h1>{esc(req.get('summary') or 'Lavorazione corrente')}</h1><div class="decision {sc(completion.get('eligible'))}">{release}</div><p>Sessione <code>{esc(state.get('session_id'))}</code>. Questa pagina consente a giurista, curatore e redazione di capire <strong>perché</strong> il capitolo è o non è consegnabile, senza esporre chain-of-thought.</p>{('<div class="block"><strong>Blocchi aperti</strong><ul>'+''.join(f'<li>{esc(x)}</li>' for x in block)+'</ul></div>') if block else '<div class="good"><strong>Nessun blocco di completamento registrato.</strong></div>'}</header>
<div class="grid">{pill('Ammissione',(admission.get('status') or 'NON REGISTRATA'))}{pill('Reticolo epistemico',ret.get('status','NON ESEGUITO'))}{pill('Contratto di generazione',gen.get('status','NON CREATO'))}{pill('DoD',f'{done}/{len(dod)}')}{pill('Fonti',source_intel.get('coverage_status','NOT_STARTED'))}{pill('Qualità',quality.get('status','NOT_RUN'))}{pill('Simulazioni',sim.get('status','NOT_RUN'))}{pill('Compressione',comp.get('status','NOT_RUN'))}</div>
<section><h2>1. Mandato e parametri editoriali accettati</h2><p><strong>Richiesta:</strong> {esc(req.get('raw',''))}</p><p class="why"><strong>Come leggerlo:</strong> questi parametri sono il patto editoriale con l'utente. Devono comparire nei DoD e non possono cambiare silenziosamente durante la redazione.</p><table><tbody>{''.join(f'<tr><th>{esc(k)}</th><td>{esc(v)}</td></tr>' for k,v in setup.get('accepted',{}).items()) or '<tr><td class="muted">Setup non ancora accettato</td></tr>'}</tbody></table></section>
<section><h2>2. Mappa epistemica del corpus</h2><div class="grid">{pill('Unità epistemiche',ret.get('node_count',len(units)))}{pill('Relazioni',ret.get('relation_count',len(rels)))}{pill('Copertura locator',ret.get('material_locator_coverage','n/a'))}{pill('Unità connesse',ret.get('connected_material_coverage','n/a'))}{pill('Legami tra capitoli',ret.get('cross_chapter_relations',len(cross)))}{pill('Contraddizioni',ret.get('contradiction_relations',len(contradictions)))}</div><p class="why"><strong>Significato:</strong> ogni tesi, regola, definizione, eccezione o qualificazione rilevante deve essere atomizzata, localizzata nel testo di origine e collegata al resto dell'opera prima che inizi la nuova redazione.</p><details open><summary><strong>Unità epistemiche</strong></summary><table><thead><tr>{head(unit_cols)}</tr></thead><tbody>{table_rows(units,unit_cols)}</tbody></table></details><details><summary><strong>Relazioni del reticolo</strong></summary><table><thead><tr>{head(rel_cols)}</tr></thead><tbody>{table_rows(rels,rel_cols)}</tbody></table></details></section>
<section><h2>3. Continuità monografica con i capitoli precedenti</h2><p class="why"><strong>Obiettivo editoriale:</strong> mostrare che il nuovo capitolo sviluppa l'opera, non ricomincia da zero e non replica materiale già svolto.</p><table><thead><tr><th>Capitolo origine</th><th>Relazione</th><th>Capitolo destinazione</th><th>Elemento precedente</th><th>Elemento collegato</th></tr></thead><tbody>{''.join(f'<tr><td>{esc(x["from"])}</td><td>{esc(x["relation"])}</td><td>{esc(x["to"])}</td><td>{esc(x["subject"])}</td><td>{esc(x["target"])}</td></tr>' for x in cross) or '<tr><td colspan="5" class="muted">Nessun legame inter-capitolo registrato</td></tr>'}</tbody></table><p><strong>Duplicazioni quasi testuali:</strong> {esc((quality.get('cross_chapter_duplication') or {}).get('status','NOT_EVALUATED'))}.</p></section>
<section><h2>4. Fonti, bibliografia e claim</h2><p class="why"><strong>Tre controlli distinti:</strong> fonte realmente letta; claim circostanziato con pinpoint; richiamo rintracciabile nell'artefatto finale.</p><table><thead><tr>{head(source_cols)}</tr></thead><tbody>{table_rows(sources,source_cols,'Nessuna fonte registrata')}</tbody></table><div class="grid">{pill('Claim materiali',sum(1 for c in claims if c.get('material',True)))}{pill('Evidence locator',len(evidence))}{pill('Apparato visibile',(quality.get('reference_apparatus') or {}).get('status','NOT_EVALUATED'))}{pill('Tracciabilità claim',(quality.get('claim_traceability') or {}).get('status','NOT_EVALUATED'))}</div></section>
<section><h2>5. Inferenze forti e scelte interpretative</h2><p class="why"><strong>Regola:</strong> una inferenza forte non è presentata come fatto. Deve indicare premesse, ponte sintetico e condizione che potrebbe smentirla.</p><table><thead><tr><th>Claim</th><th>Premesse</th><th>Ponte inferenziale</th><th>Falsificatore</th><th>Stato</th></tr></thead><tbody>{''.join(f'<tr><td>{esc(c.get("text"))}</td><td>{esc(c.get("premise_claim_ids",[]))}</td><td>{esc(c.get("inference_bridge"))}</td><td>{esc(c.get("falsifier"))}</td><td>{esc(c.get("status"))}</td></tr>' for c in inference) or '<tr><td colspan="5" class="muted">Nessuna inferenza forte registrata</td></tr>'}</tbody></table></section>
<section><h2>6. Definition of Done e qualità editoriale</h2><table><thead><tr>{head(dod_cols)}</tr></thead><tbody>{table_rows(dod,dod_cols,'DoD non ancora congelati')}</tbody></table><div class="grid">{pill('Corpo parole',quality.get('body_word_count','n/a'))}{pill('Lunghezza',quality.get('length_status','NOT_RUN'))}{pill('Continuità stile',(quality.get('style') or {}).get('status','NOT_RUN'))}{pill('No novelty vs DoD',metrics.get('dod_no_novelty_streak',0))}</div></section>
<section><h2>7. Simulazioni, saturazione e compressione finale</h2><p class="why"><strong>Perché serve:</strong> prima della consegna il capitolo viene stressato contro omissioni, contraddizioni, perdita di fonti/qualificazioni, duplicazioni, deriva terminologica, inferenze non supportate, conflitti temporali, drift stilistico e perdita da compressione.</p><div class="grid">{pill('Casi simulati',sim.get('cases',0))}{pill('Seed',len(sim.get('seeds',[])))}{pill('Famiglie edge',len(sim.get('families',[])))}{pill('Failure',sim.get('failures','n/a'))}{pill('Escape',sim.get('escapes','n/a'))}{pill('Compressione',comp.get('status','NOT_RUN'))}</div><p><strong>Unità obbligatorie perse in compressione:</strong> {esc(comp.get('lost_required_unit_ids',[]))}. <strong>Nuove unità materiali introdotte:</strong> {esc(comp.get('added_material_unit_ids',[]))}.</p></section>
<section><h2>8. Contraddizioni, limiti e benchmark</h2><p><strong>Contraddizioni aperte:</strong> {esc(len([c for c in contradictions if c.get('status','OPEN')!='RESOLVED']))}.</p><table><thead><tr><th>Limite</th><th>Impatto</th><th>Mitigazione</th></tr></thead><tbody>{table_rows(limits,[('Limite','id'),('Impatto','impact'),('Mitigazione','mitigation')],'Nessun limite registrato')}</tbody></table><p><strong>Benchmark monografico:</strong> {esc(bench.get('monograph','non richiesto/non eseguito'))}; integrità: {esc((bench.get('score') or {}).get('blind_integrity','n/a'))}.</p></section>
<section><h2>9. Artefatti e controllo finale</h2><table><thead><tr>{head(art_cols)}</tr></thead><tbody>{table_rows(artifacts,art_cols,'Nessun artefatto')}</tbody></table><p><strong>Decisione finale:</strong> {release}. <strong>Motivo del gate:</strong> {esc(completion.get('reason','non ancora valutato'))}.</p></section>
<footer class="muted"><p>Dashboard di sessione Juriscribe. Gli indicatori sono evidenze operative e controlli di coerenza; non sostituiscono il giudizio giuridico del responsabile scientifico.</p></footer>
</main></body></html>'''
    out=Path(output); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(page,encoding='utf-8'); return out
