"""Public orchestration facade.

Compression & Consolidation is layered last. The current C&C v2 overlay adds an
executable editorial reticulum while preserving the v0.12 proof and all historical
continuation/greenfield/review paths.
"""
from .orchestrator_base import *  # noqa: F401,F403
from .finalization import evaluate_completion, record_artifact, record_compression, record_final_review, record_provenance, seal_draft
from .multimode import apply_setup, audit_candidate_chapter, audit_legal_text, evaluate_completion, freeze_dods, ingest_and_mine, record_artifact, record_compression, record_continuation_coverage, record_final_review, record_provenance, record_regeneration, record_review_cycle, record_review_saturation, record_simulation, register_continuation_plan, register_semantic_mining, seal_draft, select_mode
from .delivery import evaluate_completion, record_artifact
from .semantic_delivery import evaluate_completion, record_artifact
from .generation_governance import audit_candidate_chapter, audit_legal_text, ingest_and_mine, record_final_review, record_provenance, register_plagiarism_reference, register_semantic_mining
from .artifact_governance import apply_setup, freeze_dods, record_artifact, seal_draft
from .governance_delivery import evaluate_completion
from .runtime_autopilot import apply_setup, freeze_dods, record_artifact, record_natural_language_interpretation, resolve_natural_language_interpretation, seal_draft, select_mode
from . import consolidation_atlas as _consolidation_atlas
from .runtime_cc_v2 import apply_setup, calibrate_refactoring, consolidation_gate, freeze_dods, ingest_and_mine, record_consolidation_saturation, record_simulation, register_refactoring_plan, register_semantic_mining, seal_refined_candidate, select_mode
from .runtime_v11_review import record_final_review, record_provenance, record_review_cycle
from .consolidation_completion import evaluate_completion
# Contract-check markers retained from all historical runtime layers:
# bootstrap_required=True finalization_required=True trimode_required=True editorial_standard_required=True
# delivery_boundary_required=True docx_final_documents_required=True dashboard_attachment_required=False
# dashboard_summary_surface_only=True chat_tail_docx_attachments_required=True
# materialized_delivery_required=True dashboard_state_binding_required=True artifact_first_surface_required=True
# legal_humanistic_projection_required=True semantic_dossier_freshness_required=True dashboard_inference_only=True
# evidence_traceability_required=True dashboard_artifact_recall_required=False dashboard_compressed_outcome_required=True
# generation_configuration_required=True anti_plagiarism_required=True predelivery_saturation_required=True
# artifact_atlas_required=True dashboard_complete_artifact_description_required=True
# materialized_narrative_antiplagiarism_required=True sealed_candidate_artifact_binding_required=True
# natural_language_pipeline_lock_required=True implicit_mode_change_forbidden=True
# standard_artifact_autopilot_required=True final_chapter_inference_trace_required=True
# mechanical_delivery_compliance_required=True atomic_attachment_release_required=True
# compression_consolidation_mode_required=True lossless_inventory_required=True joint_reticulum_required=True
# ten_million_mutations_required=True dual_saturation_required=True user_calibration_required=True
# minimal_surgical_refactoring_required=True canonical_immutability_required=True refined_candidate_cardinality_required=True
# peer_review_readiness_required=True consolidation_provenance_required=True consolidation_final_review_required=True
# atomic_consolidation_delivery_required=True dynamic_mode_discovery_required=True
# proof_carrying_semantics_required=True structural_substantive_claim_separation_required=True
# executable_editorial_reticulum_required=True seeded_editorial_mutation_stress_required=True
# authorized_merge_split_reorder_required=True a_level_editorial_readiness_not_journal_acceptance=True
